import pandas as pd
import numpy as np
import scipy.sparse as sp
import os
import argparse
import sys

class LDMatrix:
    """
    LD Matrix handler for genetic data.
    
    Attributes:
        ld: scipy.sparse.csr_matrix - Upper triangular LD matrix (r)
        info: pd.DataFrame - DataFrame containing SNP information (snp, a1, a2, a1f, maf)
    """
    
    def __init__(self, ld_matrix=None, chr=None, pos=None, snp=None, a1=None, a2=None, a1f=None):
        self.ld = ld_matrix
        # Wrap data into a DataFrame (ordered columns)
        maf = np.minimum(a1f, 1 - a1f) if a1f is not None else None
        het = 2 * maf * (1 - maf) if maf is not None else None
        self.info = pd.DataFrame({
            'chr': chr.astype(str) if chr is not None else None,
            'pos': pos,
            'snp': snp,
            'a1': a1,
            'a2': a2,
            'a1f': a1f,
            'maf': maf,
            'het': het
        })
    
    @staticmethod
    def _load_bim_file(bim_file):
        bim = pd.read_csv(bim_file, sep='\\s+', header=None)
        bim.columns = ['chr', 'snp', 'cm', 'pos', 'a1', 'a2']
        bim['chr'] = bim['chr'].astype(str)
        return bim
    

    @staticmethod
    def _load_afreq_file(afreq_file):
        """Load AFREQ file generated by PLINK2 --freq."""

        afreq = pd.read_csv(afreq_file, sep='\\s+')
        #afreq typical header: '#CHROM	ID	REF	ALT	PROVISIONAL_REF?	ALT_FREQS OBS_CT'
        ## =>> consider a2 as REF and a1 as ALT to be consistent with BIM file, a1f is ALT frequency
        afreq.columns = ['chr', 'snp', 'a2', 'a1', 'provisional_ref', 'a1f', 'obs_ct']
        afreq['chr'] = afreq['chr'].astype(str)
        return afreq
    
    @staticmethod
    def _load_frq_file(frq_file):
        """Load FRQ file generated by PLINK --freq"""

        frq = pd.read_csv(frq_file, sep='\\s+')
        ## in plink1 FRQ file, maf is also a1 frequency
        frq.columns = ['chr', 'snp', 'a1', 'a2', 'a1f', 'nchrobs']
        frq['chr'] = frq['chr'].astype(str)

        return frq



    @classmethod
    def from_files(cls, ld_file, bim_file, afreq_file):
        """Load LD matrix from PLINK files: LD file, BIM file, AFREQ file or FRQ file."""
        
        # Load BIM 
        print(f"Loading BIM: {bim_file}")
        bim = cls._load_bim_file(bim_file)
        
        # load FRQ
        if afreq_file.endswith('.frq'):
            print(f"Loading plink1 FRQ: {afreq_file}")
            afreq = cls._load_frq_file(afreq_file)
        elif afreq_file.endswith('.afreq'):
            print(f"Loading plink2 AFREQ: {afreq_file}")
            afreq = cls._load_afreq_file(afreq_file)
        else:
            raise ValueError("afreq_file must be either .frq or .afreq file")
        
        # Validate matching
        if not all(bim['snp'] == afreq['snp']):
            raise ValueError("SNP IDs do not match")
        if not all(bim['a2'] == afreq['a2']):
            raise ValueError("REF alleles do not match")
        if not all(bim['a1'] == afreq['a1']):
            raise ValueError("ALT alleles do not match")
        
        print("Files validated successfully")
        
        # Extract data
        snp = bim['snp'].values
        chr = bim['chr'].astype(str).values
        pos = bim['pos'].values
        a1 = bim['a1'].values
        a2 = bim['a2'].values

        a1f = afreq['a1f'].values.astype(np.float32)
        
        snp_index = {s: i for i, s in enumerate(snp)}
        n_snps = len(snp)
        print(f"Total SNPs: {n_snps:,}")
        
        # Count LD file lines
        print(f"Parsing LD file: {ld_file}")
        with open(ld_file) as f:
            n_lines = sum(1 for _ in f) - 1
        print(f"Total LD pairs: {n_lines:,}")
        
        # Preallocate arrays
        row_idx = np.empty(n_lines, dtype=np.int32)
        col_idx = np.empty(n_lines, dtype=np.int32)
        data = np.empty(n_lines, dtype=np.float32)
        
        # Parse LD file
        count = 0
        with open(ld_file) as f:
            header = next(f).strip().split()
            r_col_idx = header.index('R') if 'R' in header else 6
            
            for line_num, line in enumerate(f, 1):
                tokens = line.strip().split()
                if len(tokens) < r_col_idx + 1:
                    continue
                
                snp_a, snp_b = tokens[2], tokens[5]
                if snp_a in snp_index and snp_b in snp_index:
                    i, j = snp_index[snp_a], snp_index[snp_b]
                    if i <= j:  # upper triangular only
                        row_idx[count] = i
                        col_idx[count] = j
                        data[count] = np.float32(tokens[r_col_idx])
                        count += 1
                
                # Progress update
                if line_num % 100000 == 0:
                    progress = (line_num / n_lines) * 100
                    sys.stdout.write(f"\r  Progress: {progress:.1f}% ({count:,} entries)")
                    sys.stdout.flush()
        
        sys.stdout.write(f"\r  Progress: 100.0% ({count:,} entries)\n")
        sys.stdout.flush()
        
        # Build sparse matrix
        print("Building CSR matrix...")
        ld_matrix = sp.csr_matrix(
            (data[:count], (row_idx[:count], col_idx[:count])),
            shape=(n_snps, n_snps)
        ).astype(np.float32)
        
        return cls(ld_matrix=ld_matrix, chr=chr, pos=pos, snp=snp, a1=a1, a2=a2, a1f=a1f)
    
    
    def get_full_ld_matrix(self):
        """Reconstruct full symmetric LD matrix."""
        mat = self.ld + self.ld.T 
        mat.setdiag(1.0)
        return mat

    def get_full_ld_matrix_sq(self):
        """Get LD r-squared matrix."""
        return self.get_full_ld_matrix().power(2)
    
    def __repr__(self):
        return (f"LDMatrix(n_snps={len(self.info.snp):,}, nnz={self.ld.nnz:,},"
                f"density={self.ld.nnz/(self.ld.shape[0]**2)*100:.4f}%),"
                f"n variants={len(self.info.snp)})")

    def save_data(self, output_dir):
        """Save LD matrix to ld.npz and info to info.tsv in the specified directory.
        
        Args:
            output_dir: Directory path where ld.npz and info.tsv will be saved.
        """
        # Create directory if it doesn't exist
        os.makedirs(output_dir, exist_ok=True)
        
        # Save LD matrix
        ld_file = os.path.join(output_dir, 'ld.npz')
        np.savez(
            ld_file,
            ld_data=self.ld.data,
            ld_indices=self.ld.indices,
            ld_indptr=self.ld.indptr,
            ld_shape=self.ld.shape,
        )
        print(f"Saved LD matrix to {ld_file}! File size: {os.path.getsize(ld_file) / (1024**2):.2f} MB")
        
        # Save info dataframe
        info_file = os.path.join(output_dir, 'info.tsv')
        self.info.to_csv(info_file, sep='\t', index=False)
        print(f"Saved info to {info_file}! File size: {os.path.getsize(info_file) / (1024**2):.2f} MB")

    @classmethod
    def load_data(cls, input_dir):
        """Load LD matrix from ld.npz and info from info.tsv in the specified directory.
        
        Args:
            input_dir: Directory path containing ld.npz and info.tsv files.
        """
        # Load LD matrix
        ld_file = os.path.join(input_dir, 'ld.npz')
        with np.load(ld_file, allow_pickle=False) as data:
            ld_matrix = sp.csr_matrix(
                (data['ld_data'], data['ld_indices'], data['ld_indptr']),
                shape=tuple(data['ld_shape'])
            )
        
        # Load info dataframe
        info_file = os.path.join(input_dir, 'info.tsv')
        info_df = pd.read_csv(info_file, sep='\t')
        
        print(f"Loaded successfully from {input_dir}")
        return cls(
            ld_matrix=ld_matrix,
            chr=info_df['chr'].values,
            pos=info_df['pos'].values,
            snp=info_df['snp'].values,
            a1=info_df['a1'].values,
            a2=info_df['a2'].values,
            a1f=info_df['a1f'].values
        )


def ldmat(ld_file, bim_file, afreq_file, output_dir):
    """Construct LD matrix from PLINK files and save to directory.
    Args:
        ld_file (str): Path to PLINK LD file.
        bim_file (str): Path to PLINK BIM file.
        afreq_file (str): Path to PLINK AFREQ or FRQ file.
        output_dir (str): Directory path to save ld.npz and info.tsv files.
    """
    ld_matrix = LDMatrix.from_files(ld_file, bim_file, afreq_file)
    print("LD matrix constructed successfully.")
    ld_matrix.save_data(output_dir)


def merge(ld_dir, output_dir):
    """Merge LD matrices from multiple chromosomes stored in separate directories.
    Args:
        ld_dir (str): Parent directory containing subdirectories chr1.ldmat,..., chr22.ldmat that have ld.npz and info.tsv files in each.
        output_dir (str): Directory path to save merged ld.npz and info.tsv files.
    """

    # Initialize variables for merging
    merged_ld_data = []
    merged_ld_indices = []
    merged_ld_indptr = [0]
    merged_info_dfs = []

    # Process each chromosome
    for chr_num in range(1, 23):
        chr_dir = os.path.join(ld_dir, f"chr{chr_num}.ldmat")
        ld_file = os.path.join(chr_dir, 'ld.npz')
        info_file = os.path.join(chr_dir, 'info.tsv')
        
        if not os.path.exists(ld_file) or not os.path.exists(info_file):
            print(f"LD files not found for chromosome {chr_num}: {chr_dir}")
            exit(1)

        print(f"Loading LD matrix for chromosome {chr_num}...")
        
        # Load LD matrix
        with np.load(ld_file, allow_pickle=False) as data:
            ld_data = data['ld_data']
            ld_indices = data['ld_indices']
            ld_indptr = data['ld_indptr']
        
        # Load info dataframe
        info_df = pd.read_csv(info_file, sep='\t')
        
        # Adjust indices for merging
        offset = sum(len(df) for df in merged_info_dfs)
        merged_ld_data.append(ld_data)
        merged_ld_indices.append(ld_indices + offset)
        merged_ld_indptr.extend(ld_indptr[1:] + merged_ld_indptr[-1])
        
        # Merge info dataframes
        merged_info_dfs.append(info_df)

    # Combine sparse matrix components
    merged_ld_data = np.concatenate(merged_ld_data)
    merged_ld_indices = np.concatenate(merged_ld_indices)
    merged_ld_indptr = np.array(merged_ld_indptr)
    
    # Concatenate info dataframes
    merged_info = pd.concat(merged_info_dfs, ignore_index=True)

    # Create the merged sparse matrix
    n_snps = len(merged_info)
    merged_ld_matrix = sp.csr_matrix((merged_ld_data, merged_ld_indices, merged_ld_indptr), shape=(n_snps, n_snps))

    # Save the merged LD matrix
    print(f"Saving merged LD matrix to {output_dir}...")
    os.makedirs(output_dir, exist_ok=True)
    
    # Save LD matrix
    ld_out_file = os.path.join(output_dir, 'ld.npz')
    np.savez(
        ld_out_file,
        ld_data=merged_ld_matrix.data,
        ld_indices=merged_ld_matrix.indices,
        ld_indptr=merged_ld_matrix.indptr,
        ld_shape=merged_ld_matrix.shape,
    )
    print(f"Saved LD matrix to {ld_out_file}")
    
    # Save info dataframe
    info_out_file = os.path.join(output_dir, 'info.tsv')
    merged_info.to_csv(info_out_file, sep='\t', index=False)
    print(f"Saved info to {info_out_file}")
    print("Merged LD matrix saved successfully.")


def test (ldmat_file_legacy, ldmat_dir_new):
    """Test function to compare legacy and new LD matrix formats.
    Args:
        ldmat_file_legacy (str): Path to legacy LD matrix .mat file.
        ldmat_dir_new (str): Directory path containing ld.npz and info.tsv files.
    """
    import mat73
    print(f"Loading legacy LD matrix from {ldmat_file_legacy}...")
    mat = mat73.loadmat(ldmat_file_legacy)
    ld1, maf1 = mat['LDmat'], mat['mafvec']

    print(f"Loading new LD matrix from {ldmat_dir_new}...")
    ld_obj = LDMatrix.load_data(ldmat_dir_new)
    ld2 = ld_obj.get_full_ld_matrix()
    maf2 = ld_obj.info.maf.values

    # Compare shapes
    assert ld1.shape == ld2.shape, "LD matrix shapes do not match"
    assert len(maf1) == len(maf2), "MAF lengths do not match"
    print("Shapes match successfully.")
    
    # Compare LD values
    dif = (ld1 - ld2).data
    num_diff = np.sum(np.abs(dif) > 1e-4)
    print(f"Number of LD entries differing > 1e-4: {num_diff:,}")

    max_diff_ld = dif.max()
    print(f"Maximum difference in LD values: {max_diff_ld:.6e}")
    
    # compare MAF values
    het1 = 2 * maf1 * (1 - maf1)
    het2 = 2 * maf2 * (1 - maf2)
    diff_het = np.abs(het1 - het2).max()

    print(f"Maximum difference in heterozygosity: {diff_het:.6e}")

    ## test nnz
    nnz1 = ld1.nnz
    nnz2 = ld2.nnz
    dif = abs(nnz1 - nnz2)
    print(f"NNZ legacy: {nnz1:,}, new: {nnz2:,}, difference: {dif:,}")


def main():
    parser = argparse.ArgumentParser(description='Convert PLINK LD to NumPy and merge LD chromosome 1-22 files into one.')
    subparsers = parser.add_subparsers(dest="task", required=True, help="Task to perform.")

    # task 1: ld matrix construction
    ld_parser = subparsers.add_parser("ldmat", help="Run LD matrix construction task")
    ld_parser.add_argument("--ld", required=True, help="Path to LD file")
    ld_parser.add_argument("--bim", required=True, help="Path to BIM file")
    ld_parser.add_argument("--afreq", required=True, help="Path to AFREQ file")
    ld_parser.add_argument("--out", required=True, help="Output directory for saving ld.npz and info.tsv")

    # task 2: merge ld matrices
    merge_parser = subparsers.add_parser("merge", help="Merge LD matrices")
    merge_parser.add_argument("--ld_dir", required=True, help="Parent directory containing subdirectories chr1/ to chr22/ with ld.npz and info.tsv")
    merge_parser.add_argument("--output_dir", required=True, help="Output directory for merged ld.npz and info.tsv")

    # task 3: test legacy vs new format

    test_parser = subparsers.add_parser("test", help="Run test task")
    test_parser.add_argument("--matlab_legacy", help="Path to matlab LD matrix (legacy format)")
    test_parser.add_argument("--ldmat", help="Directory path containing ld.npz and info.tsv files (new format)")


    args = parser.parse_args()

    ## Execute tasks
    if args.task == "ldmat":
        ldmat(args.ld, args.bim, args.afreq, args.out)

    elif args.task == "merge":
        merge(args.ld_dir, args.output_dir)

    elif args.task == "test":
        test(args.matlab_legacy, args.ldmat)

    else:
        parser.print_help()
    
if __name__ == "__main__":
    main()
